export const AUTH = {
    AUTH_USER: 'AUTH_USER',
    UNAUTH_USER: 'UNAUTH_USER',
};

export const USER = {
    SET_USER: 'SET_USER',
    CLEAR_USER: 'CLEAR_USER',
};

export const ACCOUNT_INFO = {
    SET_ACCOUNT_INFO: 'SET_ACCOUNT_INFO',
    CLEAR_ACCOUNT_INFO: 'CLEAR_ACCOUNT_INFO',
};

export const AUTH_INFO = {
    SET_AUTH_INFO: 'SET_AUTH_INFO',
    CLEAR_AUTH_INFO: 'CLEAR_AUTH_INFO',
};

export const NEW_RELEASES = {
    SET_NEW_RELEASES: 'SET_NEW_RELEASES',
    CLEAR_NEW_RELEASES: 'CLEAR_NEW_RELEASES',
};

export const USER_HISTORY = {
    SET_USER_HISTORY: 'SET_USER_HISTORY',
    CLEAR_USER_HISTORY: 'CLEAR_USER_HISTORY',
};

export const YANDEX_CHART = {
    SET_YANDEX_CHART: 'SET_YANDEX_CHART',
    CLEAR_YANDEX_CHART: 'CLEAR_YANDEX_CHART',
};

export const NON_MUSIC_BLOCKS = {
    SET_NON_MUSIC_BLOCKS: 'SET_NON_MUSIC_BLOCKS',
    CLEAR_NON_MUSIC_BLOCKS: 'CLEAR_NON_MUSIC_BLOCKS',
};

export const PLAYER = {
    SET_TRACK_PLAYER: 'SET_TRACK_PLAYER',
    CLEAR_TRACK_PLAYER: 'CLEAR_TRACK_PLAYER',
    SET_PLAYER_STATE: 'SET_PLAYER_STATE',
    CLEAR_PLAYER_STATE: 'CLEAR_PLAYER_STATE',
};